"""Removed is_veg column from restaurant_menu_item table

Revision ID: 3b25df26d7c5
Revises: 5156bad6fd05
Create Date: 2025-12-18 10:37:48.153269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b25df26d7c5'
down_revision: Union[str, Sequence[str], None] = '5156bad6fd05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_menu_items', 'is_veg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_menu_items', sa.Column('is_veg', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
